### ISSUE TITLE
Use genesisEpoch instead of zero-epoch in ExecutableQueueHelper's push function

### ISSUE THREAD

**Issue by dnkolegov** [consensus-shipyard/ipc-solidity-actors#79]
Use genesisEpoch instead of zero-epoch in the ExecutableQueueHelper's push function:
https://github.com/LimeChain/filecoin-ipc-actors-fevm/blob/d247b20a4dd6ff41c6b9efad142cc05ffc2f8853/src/lib/ExecutableQueueHelper.sol#L7

**Comment by arrusev** [comment]
the early return `if (epoch == 0) return;` considers that the epoch cannot be 0, since it is the default value of `uint` type in solidity.
So i think its better to assign `genesisEpoch` to the current active epoch, calculated based on the current block number instead of hard coding it to 0. When we use dynamic calculation of the epoch, it cannot be 0
